const productList = [
  {
    id: 1,
    name: "Apples",
    description: "A bag of fresh, juicy apples",
    price: 2.99,
    category: "fruits",
  },
  {
    id: 2,
    name: "Bread",
    description: "A loaf of freshly baked bread",
    price: 1.99,
    category: "bakery",
  },

  {
    id: 3,
    name: "Milk",
    description: "A carton of whole milk",
    price: 3.49,
    category: "dairy",
  },
  {
    id: 4,
    name: "Eggs",
    description: "A dozen free-range eggs",
    price: 2.99,
    category: "dairy",
  },
  {
    id: 5,
    name: "Carrots",
    description: "A bunch of fresh carrots",
    price: 1.99,
    category: "vegetables",
  },
  {
    id: 6,
    name: "Potatoes",
    description: "A bag of fresh potatoes",
    price: 2.49,
    category: "vegetables",
  },
  {
    id: 7,
    name: "Namkeen Mixture",
    description: "A pack of spicy namkeen mixture",
    price: 3.99,
    category: "namkeens",
  },
  {
    id: 8,
    name: "Dark Chocolate",
    description: "A bar of 70% dark chocolate",
    price: 4.99,
    category: "biscuits_chocolates",
  },
  {
    id: 9,
    name: "Oranges",
    description: "A bag of juicy oranges",
    price: 3.99,
    category: "fruits",
  },
  {
    id: 10,
    name: "Baguette",
    description: "A freshly baked baguette",
    price: 2.49,
    category: "bakery",
  },
  {
    id: 11,
    name: "Cheese",
    description: "A block of cheddar cheese",
    price: 4.99,
    category: "dairy",
  },
  {
    id: 12,
    name: "Butter",
    description: "A tub of unsalted butter",
    price: 3.99,
    category: "dairy",
  },
  {
    id: 13,
    name: "Lettuce",
    description: "A head of fresh lettuce",
    price: 1.99,
    category: "vegetables",
  },
  {
    id: 14,
    name: "Onions",
    description: "A bag of fresh onions",
    price: 2.99,
    category: "vegetables",
  },
  {
    id: 15,
    name: "Aloo Bhujia",
    description: "A pack of spicy aloo bhujia",
    price: 1.99,
    category: "namkeens",
  },
];

const orderList = [
  {
    id: 12345678,
    amount: 2.99,
    date: "2023-04-10",
    items: ["Apples", "Bread", "Milk"],
    userRating: 4,
  },
  {
    id: 87654321,
    amount: 4.49,
    date: "2023-04-09",
    items: ["Eggs", "Carrots", "Potatoes"],
    userRating: 5,
  },
  {
    id: 23456789,
    amount: 1.99,
    date: "2023-04-08",
    items: ["Namkeen Mixture", "Dark Chocolate", "Oranges"],
    userRating: 1,
  },
  {
    id: 98765432,
    amount: 3.99,
    date: "2023-04-07",
    items: ["Baguette", "Cheese", "Butter"],
    userRating: 3,
  },
  {
    id: 34567890,
    amount: 2.49,
    date: "2023-04-06",
    items: ["Lettuce", "Onions", "Aloo Bhujia"],
    userRating: 0,
  },
];

const addressList = [
  {
    id: 12345678,
    street: "123 Alex view",
    city: "Gurgaon",
    state: "Haryana",
    country: "India",
    pincode: "1212333",
    defaultAddress: false,
  },
  {
    id: 87654321,
    street: "H.No. 353, Gali 12",
    city: "ArjunGarh",
    state: "New Delhi",
    country: "India",
    pincode: "122324",
    defaultAddress: false,
  },
  {
    id: 23456789,
    street: "6th Floor, Flat no 632, Anusandhan Apartements",
    city: "Ranchi",
    state: "UP",
    country: "India",
    pincode: "122324",
    defaultAddress: false,
  },
  {
    id: 98765432,
    street: "456 Maple Ave",
    city: "Somewhere City",
    state: "CheczA1B2C3",
    country: "Canada",
    pincode: "A1B 2C3",
    defaultAddress: false,
  },
  {
    id: 34567890,
    street: "123 Main St",
    city: "Anytown",
    state: "Anytown",
    country: "USA",
    pincode: "12345",
    defaultAddress: false,
  },
];

export { productList, orderList, addressList };
